"""
One-shot recompute of every run's stored stats from its CSV, under the
current analysis definitions.

Re-run whenever a stats definition changes: because the stored numbers cannot
be recovered with pure SQL, every run's CSV is reloaded and re-summarized with
analysis.calculate_run_stats, the same function the live pipeline uses.

Three definitions have moved so far:

  * schema v3 changed what "present imagery" means — a pano the provider
    returned but whose capture date we couldn't read (status NO_DATE) now
    counts toward both coverage and pano totals instead of sitting in the
    status_other error bucket (see analysis.PRESENT_STATUSES).
  * issue #213 narrowed the capture-date columns to dates that can actually be
    true, and for gsv to official '© Google' imagery. This one must be applied
    to the WHOLE series in one pass: a half-recomputed city would show a run
    history mixing two definitions of "median age", which reads as a trend that
    never happened.
  * issue #226 widened what the LOADER can read. fileutils.load_city_csv_file
    parsed capture_date with a strict '%Y-%m-%d', so the legacy pre-2026 runs
    that carry MONTH precision (and are never rewritten) had every date coerced
    to NaT while their pano counts stayed perfect — catalog rows that looked
    fully populated with NULL oldest/newest/median. Note what that means for
    this script: it reads through the same loader, so the 2026-08-18 full-series
    #213 pass processed every affected run and left them NULL. A repair handle
    is only as permissive as its reader.
  * issue #367 narrowed what "covered" means for gsv: a pano beyond
    analysis.GSV_QUERY_RADIUS_M (50 m) of its query point is read as status
    OUT_OF_RADIUS, i.e. no pano for that point. The rule is applied by the same
    loader this script reads through, so the pass inherits it with no copy of
    its own; each report line names how many rows it reclassified. Measured on
    a 60-city archived sample, that is 10.4% of covered points -- a large move
    for a published coverage number, so this one too belongs to the WHOLE gsv
    series in one pass.

Columns refreshed per run: total_points, status_ok, status_no_date,
status_zero_results, status_flat_only, status_out_of_radius, status_other,
unique_panos, unique_google_panos, coverage_rate_pct,
any_imagery_coverage_rate_pct, oldest/newest_capture_date,
median_pano_age_years, query_radius_m.

Per-run JSON summaries are not regenerated by default (they refresh on each
city's next run), but --regenerate-json rebuilds them for runs whose CSV holds
an implausible capture date, whose capture-date columns this pass moves, or
whose CSV holds a gsv pano beyond the query radius (issue #367).
Both are published files whose all_panos block and capture-year histogram hold
numbers we now know are wrong, and the city page reads them for the current AND
older snapshots. The second reason is not redundant with the first — see the
comment at the trigger itself: measured on issue #226's affected runs, 3 of 8
carried no impossible date at all, and rebuilding only on reason one would have
left them publishing NULL ages.

That second trigger has a size, and it is not small. It fires on ANY moved
capture-date column, so the first pass that also applies a date-definition
change rebuilds a large fraction of the series rather than the handful of runs
the definition was written for. Measured over every gsv run in a 1,157-run
catalog that had not yet taken issue #213's backfill: 405 runs, 35.0%, move a
date column — and only 8 of those are #226's. Each is a second full read of its
CSV on top of this loop's own, over a ~15 GB corpus. That is the cost of the
repair rather than a defect (those published files hold pre-#213 numbers), but
budget hours rather than minutes, and pass --provider gsv: without it the
trigger also reaches the Mapillary census runs, whose CSVs are millions of rows
apiece. Measurement and method: docs/experiments/capture-date-precision.md.

Two published artifacts are rebuilt either way, and they are not
interchangeable: cities.json.gz, which the overview site reads coverage from,
and driving_plan.json.gz, which is the ONLY published artifact that reads the
catalog columns this script repairs (json_summarizer._observation_block takes
newest_capture_date and median_pano_age_years straight from `runs`, while the
aggregate's age stats come from the per-run JSONs). Skipping it would leave
driving.html showing the pre-repair dates — and the driven_unplanned verdicts
derived from them — until some later unrelated `scheduler run-due`.

Idempotent: a run whose stored stats already match is left untouched. Runs
whose CSV is missing (skipped, reported) keep their existing values.

THE MAPILLARY QUALITY BACKFILL (issue #321)
--regenerate-json-mapillary-meta is a separate mode, and it skips everything
above: no stats pass, no catalog write. Issue #321 added a `quality` block
(the quality_score distribution and its on-foot split) to every Mapillary
run's `mapillary_meta`, and a run summarized before that deploy lacks it. The
mode, which requires --provider mapillary, rebuilds the per-run JSON of
exactly the runs whose JSON lacks `mapillary_meta.quality` AND whose CSV
header carries `quality_score` -- the header line only, never a census load,
decides. The ~129 runs collected before 2026-07-24 have no such column and
stay ABSENT, never zero; the report counts them.

Its cost is one full census reload per selected run (regenerate_run_json,
the live pipeline's own writer), and a Mapillary census is up to millions of
rows: on production that is HOURS. Run it in the daytime ops window, never
inside a night: --execute is refused while a `run-due` is in flight on this
machine (`scheduler._run_due_in_flight`, as recompute_run_diffs.py does),
because the nightly tail writes cities.json.gz through the same temp name and
the summarizer tail is the per-city memory high-water mark. Only this mode is
gated; the stats pass above keeps its existing behaviour. A dry run proceeds
and says a batch is running.

Usage:
    python scripts/recompute_run_stats.py                        # dry run
    python scripts/recompute_run_stats.py --execute              # apply
    python scripts/recompute_run_stats.py --provider gsv \\
        --regenerate-json --execute        # issue #213's and #226's repair on prod
    python scripts/recompute_run_stats.py --provider mapillary \\
        --regenerate-json-mapillary-meta   # issue #321's backfill: list only
    python scripts/recompute_run_stats.py --provider mapillary \\
        --regenerate-json-mapillary-meta --execute   # ...and rebuild (daytime)

--provider gsv is not just a filter there: --regenerate-json re-reads every
rebuilt run's CSV, and a Mapillary census run is millions of rows.
"""

import argparse
import gzip
import json
import logging
import math
import os
import sys
from datetime import date

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from streetscape_metadata_tracker import db  # noqa: E402
from streetscape_metadata_tracker.analysis import (  # noqa: E402
    GSV_QUERY_RADIUS_M,
    calculate_run_stats,
    implausible_capture_date_count,
    out_of_radius_count,
)
from streetscape_metadata_tracker.fileutils import load_city_csv_file  # noqa: E402
from streetscape_metadata_tracker.json_summarizer import (  # noqa: E402
    generate_aggregate_v2,
    generate_driving_plan_summary,
    regenerate_run_json,
)
from streetscape_metadata_tracker.mapillary_quality import has_quality_column  # noqa: E402
from streetscape_metadata_tracker.naming import KNOWN_PROVIDERS  # noqa: E402
from streetscape_metadata_tracker.paths import get_default_data_dir  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# Stat columns owned by calculate_run_stats that this script refreshes.
STAT_COLUMNS = (
    "total_points",
    "status_ok",
    "status_no_date",
    "status_zero_results",
    "status_flat_only",
    "status_out_of_radius",
    "status_other",
    "unique_panos",
    "unique_google_panos",
    "coverage_rate_pct",
    "any_imagery_coverage_rate_pct",
    "oldest_capture_date",
    "newest_capture_date",
    "median_pano_age_years",
    "query_radius_m",
)
# num_flat_images (issue #116) is deliberately NOT recomputed here: it is the
# flat-image census magnitude, a Mapillary-downloader artifact that the CSV
# doesn't preserve (flat-only points collapse to one FLAT_ONLY row). Reloading
# the CSV can't reconstruct it, so it is left untouched.

# The subset of STAT_COLUMNS derived from capture dates. A run whose values here
# MOVE in this pass is one whose published per-run JSON is wrong too -- see the
# --regenerate-json trigger below.
DATE_COLUMNS = (
    "oldest_capture_date",
    "newest_capture_date",
    "median_pano_age_years",
)
# Checked rather than trusted: the trigger is
# `any(c in changed for c in DATE_COLUMNS)` and `changed` is keyed by
# STAT_COLUMNS, so a name here that is not one of those is not an error -- it is
# a condition that can never be true, and the JSON rebuild silently stops
# happening for that column forever. Same posture as census._check_image_columns:
# the contract is enforced, not documented.
#
# This catches a MISSPELLED entry. The other half of the mistake -- a real stat
# column quietly DROPPED from this tuple -- is invisible to a subset check and
# is pinned instead by
# tests/test_recompute_run_stats.test_each_date_column_independently_triggers_the_json_rebuild,
# which spoils one catalog column at a time. That fixture is deliberately
# unnatural: oldest, newest and median are a min, a max and a median of one
# population and move together in any realistic run, which is exactly why a
# realistic fixture cannot see a single-column regression.
#
# `raise`, not `assert`: python -O strips asserts, and this guard is worth more
# than it costs.
if not set(DATE_COLUMNS) <= set(STAT_COLUMNS):
    raise RuntimeError(
        f"DATE_COLUMNS must be a subset of STAT_COLUMNS; "
        f"unknown: {sorted(set(DATE_COLUMNS) - set(STAT_COLUMNS))}"
    )


def _equalish(a, b) -> bool:
    """Compare stored vs recomputed values, tolerant of float noise/None."""
    if a is None or b is None:
        return a is b or a == b
    if isinstance(a, float) or isinstance(b, float):
        return math.isclose(float(a), float(b), rel_tol=0, abs_tol=1e-9)
    return a == b


def _json_has_query_radius(data_dir: str, json_filename: str | None) -> bool:
    """
    True when a run's published JSON was already built under the query radius.

    What keeps --regenerate-json's radius trigger (issue #367) idempotent: a
    run holding a far pano holds it forever -- the CSV is never rewritten -- so
    without this every later pass would rebuild every such run again. A file
    that is missing, unreadable or predates the field reads False, i.e. rebuild.
    """
    if not json_filename:
        return False
    try:
        with gzip.open(os.path.join(data_dir, json_filename), "rt", encoding="utf-8") as fh:
            coverage = json.load(fh).get("coverage") or {}
    except (OSError, EOFError, ValueError):
        return False
    return coverage.get("query_radius_m") == GSV_QUERY_RADIUS_M


def _age_delta_note(row, stats, n_implausible: int, n_out_of_radius: int = 0) -> str:
    """
    Trailing '; newest X -> Y, …' fragment for the per-run report line, or ''.

    The capture-date columns are the ones issue #213 moves, and they are the
    ones an operator wants to eyeball while a multi-hour pass scrolls by — a
    line that only ever mentions coverage and pano counts would show nothing
    changing on exactly the runs the pass exists to fix.
    """
    parts = []
    for col, label in (
        ("oldest_capture_date", "oldest"),
        ("newest_capture_date", "newest"),
    ):
        if not _equalish(row[col], stats[col]):
            parts.append(f"{label} {str(row[col])[:10]} -> {str(stats[col])[:10]}")
    if not _equalish(row["median_pano_age_years"], stats["median_pano_age_years"]):
        old, new = row["median_pano_age_years"], stats["median_pano_age_years"]
        parts.append(
            f"median age {('NULL' if old is None else f'{old:.2f}')}"
            f" -> {('NULL' if new is None else f'{new:.2f}')}"
        )
    if n_implausible:
        parts.append(f"{n_implausible} impossible date(s)")
    if n_out_of_radius:
        # Issue #367: the number an operator needs to see scroll by, since it
        # is what moved this run's coverage.
        parts.append(f"{n_out_of_radius} pano(s) beyond the query radius")
    return f"; {', '.join(parts)}" if parts else ""


def _json_has_quality_block(data_dir: str, json_filename: str | None) -> bool:
    """
    True when a run's published JSON already carries `mapillary_meta.quality`.

    What keeps the #321 backfill idempotent. A file that is missing, unreadable
    or predates the block reads False, i.e. a candidate -- the CSV header then
    decides whether there is anything to build it from.
    """
    if not json_filename:
        return False
    try:
        with gzip.open(os.path.join(data_dir, json_filename), "rt", encoding="utf-8") as fh:
            meta = json.load(fh).get("mapillary_meta") or {}
    except (OSError, EOFError, ValueError):
        return False
    return "quality" in meta


def backfill_mapillary_quality(data_dir: str, *, execute: bool, publish: bool) -> int:
    """
    Issue #321's backfill: rebuild the per-run JSON of every Mapillary run
    that lacks `mapillary_meta.quality` but whose CSV carries `quality_score`.

    Selection reads one JSON and one CSV header line per run, never a census.
    Dry run (the default) lists the selection and writes nothing; `execute`
    rebuilds each through `regenerate_run_json` (one census reload apiece, so
    hours on production) and then the aggregate, unless `publish` is False.

    Returns the process exit status: 0, or `USAGE_EXIT_CODE` when `execute`
    is refused because a `run-due` is in flight on this machine.
    """
    # Imported here so the stats pass never pays for (or depends on) the
    # scheduler module.
    from streetscape_metadata_tracker.scheduler import USAGE_EXIT_CODE, _run_due_in_flight

    in_flight = _run_due_in_flight()
    if in_flight:
        if execute:
            logger.error(
                f"A run-due is in flight on this machine ({in_flight}); refusing --execute: "
                "this backfill reloads whole censuses and rewrites cities.json.gz, so it "
                "belongs in the daytime ops window. Wait for the night to finish."
            )
            return USAGE_EXIT_CODE
        logger.warning(f"A run-due is in flight on this machine ({in_flight}); dry run only.")

    conn = db.connect(db.get_default_db_path(data_dir))
    rows = conn.execute(
        """SELECT run_id, city_id, run_date, csv_filename, json_filename
             FROM runs WHERE provider = 'mapillary'
            ORDER BY city_id, run_date"""
    ).fetchall()

    targets = []
    n_has_block = n_legacy = n_missing = 0
    for r in rows:
        if _json_has_quality_block(data_dir, r["json_filename"]):
            n_has_block += 1
            continue
        csv_path = os.path.join(data_dir, r["csv_filename"])
        if not os.path.exists(csv_path):
            logger.warning(f"CSV missing, skipping: {r['csv_filename']}")
            n_missing += 1
            continue
        if not has_quality_column(csv_path):
            n_legacy += 1
            continue
        targets.append(r)
        print(f"  {r['city_id']} [mapillary] {r['run_date']}: {r['csv_filename']}")

    print(
        f"\n{len(rows)} Mapillary runs scanned: {n_has_block} already carry the quality "
        f"block, {n_legacy} predate the quality_score column and stay absent, "
        f"{n_missing} skipped (missing CSV), {len(targets)} "
        f"{'will' if execute else 'would'} be rebuilt (one census reload each)"
    )
    if not execute:
        print("\nDry run complete. Re-run with --execute to apply (daytime only).")
        return 0

    rebuilt = 0
    for r in targets:
        if regenerate_run_json(conn, r["run_id"], data_dir) is None:
            logger.warning(f"Could not rebuild JSON for run {r['run_id']} ({r['csv_filename']})")
        else:
            rebuilt += 1
    print(f"Rebuilt {rebuilt} of {len(targets)} per-run JSON summaries.")
    if publish:
        generate_aggregate_v2(conn, data_dir)
        print(f"Regenerated aggregate: {os.path.join(data_dir, 'cities.json.gz')}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Recompute stored per-run stats from every run's CSV under "
        "the current analysis definitions (see the module docstring for which "
        "definitions have moved)"
    )
    parser.add_argument("--data-dir", default=get_default_data_dir())
    parser.add_argument(
        "--execute", action="store_true", help="Apply changes (default is a dry-run report)"
    )
    parser.add_argument(
        "--no-publish-json",
        action="store_true",
        help="Skip regenerating the published cities.json.gz and "
        "driving_plan.json.gz (catalog-only repair)",
    )
    parser.add_argument(
        "--provider",
        # From the naming contract rather than a literal: this script re-derives
        # stats for whatever run files exist, so a provider that can WRITE one
        # can always be asked about here, and a hardcoded pair silently omits
        # the newest provider from every repair.
        choices=KNOWN_PROVIDERS,
        help="Restrict to one provider's runs. Worth using for a gsv-only "
        "repair: a census CSV is millions of rows (issue #157), so "
        "loading them all costs hours and gigabytes for no change.",
    )
    parser.add_argument(
        "--regenerate-json",
        action="store_true",
        help="Also rebuild the published per-run JSON of any run whose CSV "
        "holds an implausible capture date (issue #213), whose capture-date "
        "columns this pass moves (issue #226), or which holds a gsv pano beyond "
        "the query radius (issue #367). The scan that finds the first "
        "kind is a second full pass per CSV, so it runs only under this flag; "
        "combine with --provider gsv and no --execute for a preview",
    )
    parser.add_argument(
        "--regenerate-json-mapillary-meta",
        action="store_true",
        help="Issue #321's backfill, a SEPARATE mode that skips the stats pass: "
        "rebuild the per-run JSON of every Mapillary run that lacks "
        "mapillary_meta.quality but whose CSV header carries quality_score. "
        "Requires --provider mapillary. One census reload per run (hours on "
        "production); --execute is refused while run-due is in flight",
    )
    args = parser.parse_args()

    if args.regenerate_json_mapillary_meta:
        if args.provider != "mapillary":
            parser.error("--regenerate-json-mapillary-meta requires --provider mapillary")
        if args.regenerate_json:
            parser.error(
                "--regenerate-json-mapillary-meta is its own mode; run --regenerate-json separately"
            )
        return backfill_mapillary_quality(
            args.data_dir, execute=args.execute, publish=not args.no_publish_json
        )

    conn = db.connect(db.get_default_db_path(args.data_dir))

    where = "WHERE provider = ?" if args.provider else ""
    params = (args.provider,) if args.provider else ()
    rows = conn.execute(
        f"""SELECT run_id, city_id, provider, run_date, csv_filename, json_filename,
                   total_points, status_ok, status_no_date, status_zero_results,
                   status_flat_only, status_out_of_radius, status_other,
                   unique_panos, unique_google_panos, coverage_rate_pct,
                   any_imagery_coverage_rate_pct, oldest_capture_date,
                   newest_capture_date, median_pano_age_years, query_radius_m
            FROM runs {where} ORDER BY city_id, provider, run_date""",
        params,
    ).fetchall()

    updates = []  # (run_id, {col: value})
    json_repairs = []  # (run_id, csv_filename, implausible pano count)
    n_date_moved = 0  # of those repairs, how many were triggered by a moved date
    n_radius = 0  # of those repairs, how many hold a pano beyond the query radius
    missing = 0
    for r in rows:
        csv_path = os.path.join(args.data_dir, r["csv_filename"])
        if not os.path.exists(csv_path):
            logger.warning(f"CSV missing, skipping: {r['csv_filename']}")
            missing += 1
            continue
        df = load_city_csv_file(csv_path)
        run_date = date.fromisoformat(r["run_date"])
        stats = calculate_run_stats(df, run_date, provider=r["provider"])
        changed = {c: stats[c] for c in STAT_COLUMNS if not _equalish(r[c], stats[c])}
        # Issue #367. Asked through the analysis helper rather than read off a
        # status column, so this script holds no copy of the rule.
        n_out_of_radius = out_of_radius_count(df, r["provider"])
        # A run needs its PUBLISHED json rebuilt for either of two reasons, and
        # they are genuinely different questions -- neither implies the other.
        #
        #   (1) The CSV holds an impossible capture date (issue #213). Asked of
        #       the file in hand rather than of the recomputed stats, because
        #       #213's copyright narrowing moves a catalog stat for nearly every
        #       gsv run while the file on disk is only wrong where a bad date
        #       actually reached it.
        #   (2) This pass MOVED the run's capture-date columns. The per-run JSON
        #       is generated through the same loader and the same
        #       dated_unique_panos seam as those columns, so a date column that
        #       moves under a loader or definition change is a direct signal that
        #       the published file holds the pre-fix numbers too. Issue #226 is
        #       exactly that shape and the reverse of #213's: the column moves
        #       BECAUSE the JSON's own numbers were computed wrong. Measured on
        #       the 8 affected runs in one catalog, 3 (Lagos, Nakuru, La Piedad)
        #       carry no impossible date at all, so trigger (1) alone would have
        #       left them publishing NULL ages -- and the site's age display
        #       reads the per-run JSON, not `runs` (json_summarizer's
        #       _build_provider_summary takes all_panos_age_stats and the
        #       capture-year histogram from it).
        #
        # The cost of (2) is worth stating: a future whole-series date-definition
        # change now means a whole-series JSON rebuild, and regenerate_run_json
        # re-reads each CSV. That is correct rather than merely expensive -- a
        # published file whose numbers we know are stale is the thing being fixed.
        #
        # (1) is only asked when the answer will be used. It is a second dedup +
        # date-parse pass over the whole run on top of the one calculate_run_stats
        # just did, and this loop already carries the series' dominant cost (a
        # Mapillary census CSV is millions of rows), so paying it to print a line
        # nobody asked for would roughly double the stats half of every pass.
        n_implausible = 0
        if args.regenerate_json:
            n_implausible = implausible_capture_date_count(
                df, pd.Timestamp(run_date), r["provider"]
            )
            date_moved = any(c in changed for c in DATE_COLUMNS)
            # (3) Issue #367: a gsv pano beyond the query radius. The published
            # JSON counted it as coverage, as a unique pano, and in the age
            # stats, so the file is wrong wherever the rule reclassified a row
            # -- even on a pass after the catalog was already repaired. Unless
            # the JSON is ALREADY built under the rule: the far pano never
            # leaves the CSV, so without that check this fires on every pass.
            radius_stale = bool(n_out_of_radius) and not _json_has_query_radius(
                args.data_dir, r["json_filename"]
            )
            if n_implausible or date_moved or radius_stale:
                json_repairs.append((r["run_id"], r["csv_filename"], n_implausible))
                if date_moved:
                    n_date_moved += 1
                if radius_stale:
                    n_radius += 1
        if changed:
            updates.append((r["run_id"], changed))
            nd = stats["status_no_date"]
            cov_old = r["coverage_rate_pct"]
            cov_new = stats["coverage_rate_pct"]
            print(
                f"  {r['city_id']} [{r['provider']}] {r['run_date']}: "
                f"coverage {('NULL' if cov_old is None else f'{cov_old:.1f}%')}"
                f" -> {cov_new:.1f}%, unique_panos "
                f"{r['unique_panos']} -> {stats['unique_panos']}, "
                f"status_no_date -> {nd}"
                f"{_age_delta_note(r, stats, n_implausible, n_out_of_radius)}"
            )

    print(
        f"\n{len(rows)} runs scanned, {missing} skipped (missing CSV), {len(updates)} would change"
    )
    if not args.regenerate_json:
        print(
            "Per-run JSONs not inspected; pass --regenerate-json to find and "
            "rebuild the ones holding an impossible capture date, a pano beyond "
            "the query radius, or capture-date columns this pass would move"
        )
    elif json_repairs:
        total_bad = sum(n for _, _, n in json_repairs)
        n_bad_dates = sum(1 for _, _, n in json_repairs if n)
        # "would be" on a dry run: the rebuild loop below sits after the
        # early return, so a preview that promised "will be" was describing an
        # action the preview does not take.
        #
        # The two reasons are reported separately rather than as one total: they
        # send an operator to different places (a corrupt value in the CSV vs a
        # stat definition that moved under it), and the counts overlap, so a
        # single number would hide whichever reason was rarer that pass.
        print(
            f"{len(json_repairs)} runs need their per-run JSON rebuilt "
            f"({n_bad_dates} hold an impossible capture date, {total_bad} panos "
            f"in all; {n_date_moved} have capture-date columns this pass moves; "
            f"{n_radius} hold a pano beyond the query radius); "
            f"they {'will' if args.execute else 'would'} be rebuilt"
        )

    if not args.execute:
        print("\nDry run complete. Re-run with --execute to apply.")
        return 0

    with conn:
        for run_id, changed in updates:
            assignments = ", ".join(f"{c} = ?" for c in changed)
            conn.execute(
                f"UPDATE runs SET {assignments} WHERE run_id = ?", (*changed.values(), run_id)
            )

    print(f"\nUpdated {len(updates)} runs.")

    if args.regenerate_json:
        rebuilt = 0
        for run_id, csv_filename, _ in json_repairs:
            # regenerate_run_json reloads the CSV itself. That is a second read
            # of a file this pass already had in memory, and deliberately so:
            # it is the one function that writes a per-run JSON exactly as the
            # live pipeline does, so a rebuilt file is what the next collection
            # would have written rather than a second implementation of it.
            #
            # Do NOT read a set-size bound into that justification. This comment
            # used to end "and the repaired set is dozens of runs, not
            # thousands", which held only while the trigger was #213's
            # impossible-date test alone. Trigger (2) fires on any moved
            # capture-date column, so a pass that also carries a date-definition
            # change rebuilds a large fraction of the series -- measured at 405
            # of 1,157 gsv runs, 35.0% (see the module docstring). The double
            # read is worth paying at that scale too; it is the wall clock, not
            # the correctness, that the operator needs warning about.
            if regenerate_run_json(conn, run_id, args.data_dir) is None:
                logger.warning(f"Could not rebuild JSON for run {run_id} ({csv_filename})")
            else:
                rebuilt += 1
        print(f"Rebuilt {rebuilt} of {len(json_repairs)} per-run JSON summaries.")
    if not args.no_publish_json:
        generate_aggregate_v2(conn, args.data_dir)
        print(f"Regenerated aggregate: {os.path.join(args.data_dir, 'cities.json.gz')}")
        # The driving page reads the repaired columns DIRECTLY off `runs`, so
        # it is the artifact that most needs republishing here — see the module
        # docstring. Guarded like the scheduler's tail (#167 posture): a failure
        # to rebuild the plan page must not make it look as though the catalog
        # repair, which is already committed, failed too.
        try:
            generate_driving_plan_summary(conn, args.data_dir)
            print(
                f"Regenerated driving plan: {os.path.join(args.data_dir, 'driving_plan.json.gz')}"
            )
        except Exception:
            logger.exception(
                "Driving-plan summary failed; the catalog repair is applied, but "
                "driving.html will keep its pre-repair capture dates until "
                "`scheduler regenerate-aggregate` or the next run-due rebuilds it"
            )
    return 0


if __name__ == "__main__":
    sys.exit(main())
