"""
One-shot recompute of every run's stored stats from its CSV, under the
current analysis definitions.

Re-run whenever a stats definition changes: because the stored numbers cannot
be recovered with pure SQL, every run's CSV is reloaded and re-summarized with
analysis.calculate_run_stats, the same function the live pipeline uses.

Two definitions have moved so far:

  * schema v3 changed what "present imagery" means — a pano the provider
    returned but whose capture date we couldn't read (status NO_DATE) now
    counts toward both coverage and pano totals instead of sitting in the
    status_other error bucket (see analysis.PRESENT_STATUSES).
  * issue #213 narrowed the capture-date columns to dates that can actually be
    true, and for gsv to official '© Google' imagery. This one must be applied
    to the WHOLE series in one pass: a half-recomputed city would show a run
    history mixing two definitions of "median age", which reads as a trend that
    never happened.

Columns refreshed per run: total_points, status_ok, status_no_date,
status_zero_results, status_flat_only, status_other, unique_panos,
unique_google_panos, coverage_rate_pct, any_imagery_coverage_rate_pct,
oldest/newest_capture_date, median_pano_age_years.

Per-run JSON summaries are not regenerated by default (they refresh on each
city's next run), but --regenerate-json rebuilds them for runs whose CSV holds
an implausible capture date — those are the published files whose all_panos
block and capture-year histogram carry the corrupt value, and the city page
reads them for the current AND older snapshots.

Two published artifacts are rebuilt either way, and they are not
interchangeable: cities.json.gz, which the overview site reads coverage from,
and driving_plan.json.gz, which is the ONLY published artifact that reads the
catalog columns this script repairs (json_summarizer._observation_block takes
newest_capture_date and median_pano_age_years straight from `runs`, while the
aggregate's age stats come from the per-run JSONs). Skipping it would leave
driving.html showing the pre-repair dates — and the driven_unplanned verdicts
derived from them — until some later unrelated `scheduler run-due`.

Idempotent: a run whose stored stats already match is left untouched. Runs
whose CSV is missing (skipped, reported) keep their existing values.

Usage:
    python scripts/recompute_run_stats.py                        # dry run
    python scripts/recompute_run_stats.py --execute              # apply
    python scripts/recompute_run_stats.py --provider gsv \\
        --regenerate-json --execute        # issue #213's repair on prod
"""

import argparse
import logging
import math
import os
import sys
from datetime import date

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from streetscape_metadata_tracker import db  # noqa: E402
from streetscape_metadata_tracker.analysis import (  # noqa: E402
    calculate_run_stats,
    implausible_capture_date_count,
)
from streetscape_metadata_tracker.fileutils import load_city_csv_file  # noqa: E402
from streetscape_metadata_tracker.json_summarizer import (  # noqa: E402
    generate_aggregate_v2,
    generate_driving_plan_summary,
    regenerate_run_json,
)
from streetscape_metadata_tracker.paths import get_default_data_dir  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# Stat columns owned by calculate_run_stats that this script refreshes.
STAT_COLUMNS = (
    "total_points",
    "status_ok",
    "status_no_date",
    "status_zero_results",
    "status_flat_only",
    "status_other",
    "unique_panos",
    "unique_google_panos",
    "coverage_rate_pct",
    "any_imagery_coverage_rate_pct",
    "oldest_capture_date",
    "newest_capture_date",
    "median_pano_age_years",
)
# num_flat_images (issue #116) is deliberately NOT recomputed here: it is the
# flat-image census magnitude, a Mapillary-downloader artifact that the CSV
# doesn't preserve (flat-only points collapse to one FLAT_ONLY row). Reloading
# the CSV can't reconstruct it, so it is left untouched.


def _equalish(a, b) -> bool:
    """Compare stored vs recomputed values, tolerant of float noise/None."""
    if a is None or b is None:
        return a is b or a == b
    if isinstance(a, float) or isinstance(b, float):
        return math.isclose(float(a), float(b), rel_tol=0, abs_tol=1e-9)
    return a == b


def _age_delta_note(row, stats, n_implausible: int) -> str:
    """
    Trailing '; newest X -> Y, …' fragment for the per-run report line, or ''.

    The capture-date columns are the ones issue #213 moves, and they are the
    ones an operator wants to eyeball while a multi-hour pass scrolls by — a
    line that only ever mentions coverage and pano counts would show nothing
    changing on exactly the runs the pass exists to fix.
    """
    parts = []
    for col, label in (
        ("oldest_capture_date", "oldest"),
        ("newest_capture_date", "newest"),
    ):
        if not _equalish(row[col], stats[col]):
            parts.append(f"{label} {str(row[col])[:10]} -> {str(stats[col])[:10]}")
    if not _equalish(row["median_pano_age_years"], stats["median_pano_age_years"]):
        old, new = row["median_pano_age_years"], stats["median_pano_age_years"]
        parts.append(
            f"median age {('NULL' if old is None else f'{old:.2f}')}"
            f" -> {('NULL' if new is None else f'{new:.2f}')}"
        )
    if n_implausible:
        parts.append(f"{n_implausible} impossible date(s)")
    return f"; {', '.join(parts)}" if parts else ""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Recompute stored per-run stats from every run's CSV under "
        "the current analysis definitions (see the module docstring for which "
        "definitions have moved)"
    )
    parser.add_argument("--data-dir", default=get_default_data_dir())
    parser.add_argument(
        "--execute", action="store_true", help="Apply changes (default is a dry-run report)"
    )
    parser.add_argument(
        "--no-publish-json",
        action="store_true",
        help="Skip regenerating the published cities.json.gz and "
        "driving_plan.json.gz (catalog-only repair)",
    )
    parser.add_argument(
        "--provider",
        choices=("gsv", "mapillary"),
        help="Restrict to one provider's runs. Worth using for a gsv-only "
        "repair: a Mapillary census CSV is millions of rows (issue #157), so "
        "loading them all costs hours and gigabytes for no change.",
    )
    parser.add_argument(
        "--regenerate-json",
        action="store_true",
        help="Also rebuild the published per-run JSON of any run whose CSV "
        "holds an implausible capture date (issue #213). The scan that finds "
        "those runs is a second full pass per CSV, so it runs only under this "
        "flag; combine with --provider gsv and no --execute for a preview",
    )
    args = parser.parse_args()

    conn = db.connect(db.get_default_db_path(args.data_dir))

    where = "WHERE provider = ?" if args.provider else ""
    params = (args.provider,) if args.provider else ()
    rows = conn.execute(
        f"""SELECT run_id, city_id, provider, run_date, csv_filename,
                   total_points, status_ok, status_no_date, status_zero_results,
                   status_flat_only, status_other, unique_panos,
                   unique_google_panos, coverage_rate_pct,
                   any_imagery_coverage_rate_pct, oldest_capture_date,
                   newest_capture_date, median_pano_age_years
            FROM runs {where} ORDER BY city_id, provider, run_date""",
        params,
    ).fetchall()

    updates = []  # (run_id, {col: value})
    json_repairs = []  # (run_id, csv_filename, implausible pano count)
    missing = 0
    for r in rows:
        csv_path = os.path.join(args.data_dir, r["csv_filename"])
        if not os.path.exists(csv_path):
            logger.warning(f"CSV missing, skipping: {r['csv_filename']}")
            missing += 1
            continue
        df = load_city_csv_file(csv_path)
        run_date = date.fromisoformat(r["run_date"])
        stats = calculate_run_stats(df, run_date, provider=r["provider"])
        # Which runs need their PUBLISHED json rebuilt is asked of the CSV in
        # hand, not of the recomputed stats: issue #213's copyright narrowing
        # moves a stat for nearly every gsv run, while the file on disk is only
        # wrong where an impossible date actually reached it.
        #
        # Only asked when the answer will be used. It is a second dedup +
        # date-parse pass over the whole run on top of the one calculate_run_stats
        # just did, and this loop already carries the series' dominant cost (a
        # Mapillary census CSV is millions of rows), so paying it to print a line
        # nobody asked for would roughly double the stats half of every pass.
        n_implausible = 0
        if args.regenerate_json:
            n_implausible = implausible_capture_date_count(
                df, pd.Timestamp(run_date), r["provider"]
            )
            if n_implausible:
                json_repairs.append((r["run_id"], r["csv_filename"], n_implausible))
        changed = {c: stats[c] for c in STAT_COLUMNS if not _equalish(r[c], stats[c])}
        if changed:
            updates.append((r["run_id"], changed))
            nd = stats["status_no_date"]
            cov_old = r["coverage_rate_pct"]
            cov_new = stats["coverage_rate_pct"]
            print(
                f"  {r['city_id']} [{r['provider']}] {r['run_date']}: "
                f"coverage {('NULL' if cov_old is None else f'{cov_old:.1f}%')}"
                f" -> {cov_new:.1f}%, unique_panos "
                f"{r['unique_panos']} -> {stats['unique_panos']}, "
                f"status_no_date -> {nd}"
                f"{_age_delta_note(r, stats, n_implausible)}"
            )

    print(
        f"\n{len(rows)} runs scanned, {missing} skipped (missing CSV), {len(updates)} would change"
    )
    if not args.regenerate_json:
        print(
            "Per-run JSONs not inspected; pass --regenerate-json to find and "
            "rebuild the ones holding an impossible capture date"
        )
    elif json_repairs:
        total_bad = sum(n for _, _, n in json_repairs)
        # "would be" on a dry run: the rebuild loop below sits after the
        # early return, so a preview that promised "will be" was describing an
        # action the preview does not take.
        print(
            f"{len(json_repairs)} runs hold an impossible capture date "
            f"({total_bad} panos in all); their per-run JSON "
            f"{'will' if args.execute else 'would'} be rebuilt"
        )

    if not args.execute:
        print("\nDry run complete. Re-run with --execute to apply.")
        return 0

    with conn:
        for run_id, changed in updates:
            assignments = ", ".join(f"{c} = ?" for c in changed)
            conn.execute(
                f"UPDATE runs SET {assignments} WHERE run_id = ?", (*changed.values(), run_id)
            )

    print(f"\nUpdated {len(updates)} runs.")

    if args.regenerate_json:
        rebuilt = 0
        for run_id, csv_filename, _ in json_repairs:
            # regenerate_run_json reloads the CSV itself. That is a second read
            # of a file this pass already had in memory, and deliberately so:
            # it is the one function that writes a per-run JSON exactly as the
            # live pipeline does, and the repaired set is dozens of runs, not
            # thousands.
            if regenerate_run_json(conn, run_id, args.data_dir) is None:
                logger.warning(f"Could not rebuild JSON for run {run_id} ({csv_filename})")
            else:
                rebuilt += 1
        print(f"Rebuilt {rebuilt} of {len(json_repairs)} per-run JSON summaries.")
    if not args.no_publish_json:
        generate_aggregate_v2(conn, args.data_dir)
        print(f"Regenerated aggregate: {os.path.join(args.data_dir, 'cities.json.gz')}")
        # The driving page reads the repaired columns DIRECTLY off `runs`, so
        # it is the artifact that most needs republishing here — see the module
        # docstring. Guarded like the scheduler's tail (#167 posture): a failure
        # to rebuild the plan page must not make it look as though the catalog
        # repair, which is already committed, failed too.
        try:
            generate_driving_plan_summary(conn, args.data_dir)
            print(
                f"Regenerated driving plan: {os.path.join(args.data_dir, 'driving_plan.json.gz')}"
            )
        except Exception:
            logger.exception(
                "Driving-plan summary failed; the catalog repair is applied, but "
                "driving.html will keep its pre-repair capture dates until "
                "`scheduler regenerate-aggregate` or the next run-due rebuilds it"
            )
    return 0


if __name__ == "__main__":
    sys.exit(main())
